[PATHS]
; Пути назначения для файлов. Сюда будут перемещены скачанные медиа.
movies_folder = /path/to/your/movies
series_folder = /path/to/your/tvshows

[LOGGING]
; Уровень логирования: DEBUG, INFO, WARNING, ERROR
level = INFO
; Путь к файлу логов. Убедитесь, что у пользователя есть права на запись.
log_file = /opt/mediasorter/sorter.log

[SYSTEM]
; Расширения файлов, которые скрипт будет обрабатывать как видео
video_extensions = .mkv,.avi,.mp4,.mov,.wmv,.m4v,.ts

[API]
; --- KINOPOISK (Unofficial) ---
; https://kinopoiskapiunofficial.tech
use_kp = False
kp_api_key = YOUR_KINOPOISK_API_KEY

; --- TMDB (The Movie Database) ---
; https://www.themoviedb.org/settings/api
use_tmdb = False
tmdb_api_key = YOUR_TMDB_API_KEY

; --- TVDB (The TV Database) ---
; https://thetvdb.com/api-information
use_tvdb = False
tvdb_api_key = YOUR_TVDB_API_KEY

[TELEGRAM]
; Включить или выключить уведомления в Telegram
use_telegram = False
bot_token = YOUR_TELEGRAM_BOT_TOKEN
chat_id = YOUR_TELEGRAM_CHAT_ID

[TRANSMISSION]
; Настройки подключения к Transmission RPC для удаления торрентов после обработки
host = localhost
port = 9091
; Если настроена аутентификация, введите данные ниже
username = 
password =